language: python
python: "3.7"
dist: xenial
os: linux

# ignore the virtualenv that Travis creates
# setup a secure login to CodeCov
# set env variables for different jobs
env:
  global:
    - PYENV_ROOT=$HOME/.travis-pyenv
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - secure: aU6ToQ8/23GK6QJxRKA7xBNuV3W26YoXrFMOMIPU8om22CCSd7aiN5ls6msR+cqX2cY3ozXUh/jcQqFeYrG3026gs53OVO+NSkZXVv3o9I6WaVM4wyudMXty3wAiq+1H9DWWYLKQOVInqPUmjetA1XioV3u9D2aTH+0psZUHzRCz0DrSIE7QF06YHexP4tNJayihjo3wXfHVOB+ABKb+O9ZdfCDSeUsJjeI7N1hP7+aAsa0lcgrvWevNOwlouchGliOB4qCqxAKAPsLyg9PVE/HDgHLpsWh/HnPfdiK5U8yoSIPRRn4wlCgn0bQ/xO2eFdNImHTel+cTzo6n7GNvyZU7VvxcmRdfqQAl7ix/mU255wMAziaIrJnvjJXuLO6PPTtW83Wfh54YyAX/d4bc9AKdszJUI0wa9ir3O8tSe6sY8YXe+mE83Tgh67heBqzBclofLyKF8g6IPiOefIkRFKBkIlJiB42Xbh2Zi+39BUvi6lrViCOB8DyWSkA4gjEPAKzvZSFGim9BxGPknfRknpWELn8hQ3GC9iOZ4NrAtuDl2kQshhjTVUGcEpYKjaoNROnjBZkpPT54/OweWJYW3w6uw9K8jEF63g6pWkKi2jVwtcmUp5cRuvgSaX5+1sd6T0DMNHBXYaUqMIgwdIljoDwswktvzfKtADKmO6TzbS8=
    - secure: dE2+Q6P1KrFHr0kVn9Nwzx4mRVdTP3397hXDCyOM21+kAS3Kq6yRN/J1ThU701T7y6baEfWe6ICjDA2P4RTsN6MXUBkRjr1Wn7fht5FILnla9r5hQ+t2g4mPh7jsaJr7e8Qa29cML2Jub91midyzG4b348+AHod1JoUr2Adttvs4mtrVRV8epIby8VMa9iyyP3jD+1hq2xxtqVeQeaRbU44Bs4jIcDWx7ihix7Ns1AjqVUQhxgEhNh1RUlcppiGWGwAp3iWkqYFxfoqxKDbcZ2jl7YFA0ygJVnuuzxkZ7mNMMu3/T1CuC+IObD0KPjuNksx22OEyy1SKkOEBDuByyJRftnMPfzLw5PfwN+dyVjBLkGNf0Z3xdxCqhimPZaqlvlhwES7sq09aJuy/MBfpBcCp9GXITybjsp5NzUnfdiBN0efIgeeYp8gYv3uu/JAMJD6l/DM2WVG3mjsEXoinzhaw2XmYdLIU1w5jGfvcUdN0JolUT4ci9x2HeBhcGYQfkFgfC8xqHRy3UObVIvXoeoG1SlBk86fLHosubp59R/zWbUPl7jDIWjNK2WluUNTkDlEg2WYNznEf3VRtMeqOMD7O5s0+AANa38mw+qBXVpJDKc4V3nphbR2NPEAFRBluC5qG+lTKHmxEnr/i4j6rOFum5ymBvoae6YriT13sMBc=

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv install --dev --python "3.7"
  - gem install mdl

# use a cache to improve performance
# cache pip installations
# cache pyenv installations
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache

# perform testing:
# --> run the test suite and generate coverage with Pipfile script
# --> lint the code with Pipfile script
# --> lint the README documentation with mdl
script:
  - pipenv run cover
  - pipenv run lint --check
  - mdl README.md

# report coverage information to CodeCov
after_success:
  - pipenv run codecov
  - wget https://github.com/Michionlion/pr-tag-release/releases/latest/download/pr_tag_release.sh
  - source pr_tag_release.sh

# deploy to GitHub Releases on PR merge
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  on:
    all_branches: true
    condition: $DO_GITHUB_RELEASE = true
